on: [push]

jobs:
  nibbler-test:
    runs-on: ubuntu-latest
    name: test action
    steps:
      - name: login to ghcr.io
        uses: nordseth/nibbler-action/login@main
        with:
          registry: "ghcr.io"
          username: "USERNAME"
          password: "{{ secrets.GITHUB_TOKEN }}"
      - name: build and push
        id: nibbler
        uses: nordseth/nibbler-action@main
        with:
          from-image: "registry.hub.docker.com/library/alpine:latest"
          to-images: "ghcr.io/nordseth/apline:latest"
      - name: Get output 
        run: echo "${{ steps.nibbler.outputs.image-digest }}"
