on: [push]

jobs:
  nibbler-test:
    runs-on: ubuntu-latest
    name: test action
    steps:
      - name: Test nibbler action
        id: nibbler
        uses: nordseth/nibbler-action@main
        with:
          from-image: ""
          to-images: ""
      - name: Get output 
        run: echo "${{ steps.nibbler.outputs.image-digest }}"